# Generated by Django 4.1.4 on 2023-01-03 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_rename_academic_year_academicyear_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='bertID',
            new_name='bert_ID',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='vaderID',
            new_name='vader_ID',
        ),
    ]
