# Generated by Django 4.1.4 on 2023-01-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_academicyear_end_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='id',
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='start_year',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
