# Generated by Django 4.1.4 on 2023-01-10 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=100, validators=[django.core.validators.MinLengthValidator(10)])),
                ('actual_sentiment', models.CharField(choices=[('POSITIVE', 'POSITIVE'), ('NEUTRAL', 'NEUTRAL'), ('NEGATIVE', 'NEGATIVE')], default='NEUTRAL', max_length=10)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SentimentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vader_pos', models.DecimalField(decimal_places=2, max_digits=4)),
                ('vader_neg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('bert_pos', models.DecimalField(decimal_places=2, max_digits=4)),
                ('bert_neg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hybrid_pos', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hybrid_neg', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
