# Generated by Django 4.1.4 on 2023-01-04 13:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visualizer', '0003_alter_subject_subject_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('start_year', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('end_year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BertSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('negative_score', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_ID', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strand_name', models.CharField(choices=[('ABM', 'ABM'), ('ABM-B', 'ABM-B'), ('ABMBUS', 'ABMBUS'), ('HE', 'HE'), ('HUMS', 'HUMS'), ('HUMSS', 'HUMSS'), ('ICT', 'ICT'), ('STEM', 'STEM'), ('STEM-M', 'STEM-M'), ('STEM-S', 'STEM-S'), ('STEMB', 'STEMB'), ('STEMF', 'STEMF'), ('STEMG', 'STEMG'), ('STEMMA', 'STEMMA'), ('STEMSC', 'STEMSC')], default='HUMSS', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VaderSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('negative_score', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('section_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feedback.section')),
                ('strand_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feedback.strand')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=100, validators=[django.core.validators.MinLengthValidator(10)])),
                ('actual_sentiment', models.CharField(choices=[('POSITIVE', 'POSITIVE'), ('NEUTRAL', 'NEUTRAL'), ('NEGATIVE', 'NEGATIVE')], default='NEUTRAL', max_length=10)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('academic_year_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feedback.academicyear')),
                ('bert_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feedback.bertsentiment')),
                ('student_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feedback.student')),
                ('teacher_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visualizer.teacher')),
                ('vader_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feedback.vadersentiment')),
            ],
        ),
    ]
