# Generated by Django 4.1.4 on 2023-01-26 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluatee',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.AddField(
            model_name='comment',
            name='sentiment_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.sentimentscore'),
        ),
        migrations.AddConstraint(
            model_name='evaluatee',
            constraint=models.UniqueConstraint(fields=('teacher', 'subject', 'fe'), name='unique_evaluatee'),
        ),
    ]
