# Generated by Django 4.1.4 on 2023-01-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='academic_year_ID',
            new_name='academic_year',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='bert_ID',
            new_name='bert',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='student_ID',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='teacher_ID',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='vader_ID',
            new_name='vader',
        ),
    ]
