# Generated by Django 4.1.4 on 2023-01-05 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_rename_academic_year_id_feedback_academic_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='content',
            new_name='comment',
        ),
    ]
