# Generated by Django 4.1.4 on 2023-01-03 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Academic_Year',
            new_name='AcademicYear',
        ),
        migrations.RenameModel(
            old_name='BERT_Sentiment',
            new_name='BertSentiment',
        ),
        migrations.RenameModel(
            old_name='VADER_Sentiment',
            new_name='VaderSentiment',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='bert_senti_ID',
            new_name='bertID',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='vader_senti_ID',
            new_name='vaderID',
        ),
    ]
