# Generated by Django 4.1.4 on 2023-01-26 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_comment_sentiment_score_alter_feedback_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='evaluatee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.evaluatee'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='evaluator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feedback.evaluator'),
        ),
    ]
