# Generated by Django 4.1.4 on 2023-01-05 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_rename_content_feedback_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vader_pos', models.DecimalField(decimal_places=2, max_digits=4)),
                ('vader_neg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('bert_pos', models.DecimalField(decimal_places=2, max_digits=4)),
                ('bert_neg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hybrid_pos', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hybrid_neg', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='bert',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='vader',
        ),
        migrations.AddField(
            model_name='feedback',
            name='sentiment_score',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='feedback.sentimentscore'),
            preserve_default=False,
        ),
    ]
