# Generated by Django 4.1.4 on 2023-01-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_sentimentscore_remove_feedback_bert_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BertSentiment',
        ),
        migrations.DeleteModel(
            name='VaderSentiment',
        ),
    ]
