# Generated by Django 4.1.4 on 2023-01-26 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('feedback', '0004_alter_feedback_evaluatee_alter_feedback_evaluator'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluator',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.student'),
            preserve_default=False,
        ),
    ]
