# Generated by Django 4.1.4 on 2023-01-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_rename_bertid_feedback_bert_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='end_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='start_year',
            field=models.PositiveIntegerField(),
        ),
    ]
