# Generated by Django 4.1.4 on 2023-01-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_academicyear_end_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='academic_year_ID',
            new_name='acadyear',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='student_ID',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='bert_ID',
            new_name='bert',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='teacher_ID',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='vader_ID',
            new_name='vader',
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='id',
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='start_year',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
