# Generated by Django 4.1.4 on 2023-02-10 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0002_alter_strand_strand_name'),
        ('feedback', '0005_evaluator_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='actual_sentiment',
        ),
        migrations.AddField(
            model_name='evaluatee',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='visualizer.section'),
            preserve_default=False,
        ),
    ]
