# Generated by Django 4.1.4 on 2023-01-09 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_delete_bertsentiment_delete_vadersentiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='section_ID',
        ),
        migrations.RemoveField(
            model_name='student',
            name='strand_ID',
        ),
    ]
