# Generated by Django 4.1.4 on 2023-03-13 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0006_remove_comment_actual_sentiment_evaluatee_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="comment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment",
                to="feedback.comment",
            ),
        ),
    ]
