# Generated by Django 4.1.4 on 2023-01-09 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('feedback', '0006_remove_student_section_id_remove_student_strand_id'),
        ('visualizer', '0004_academicyear_section_strand_remove_teacher_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualizer.academicyear'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='sentiment_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.sentimentscore'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
        migrations.DeleteModel(
            name='AcademicYear',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Strand',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
