# Generated by Django 4.1.4 on 2023-01-15 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='faculty_eval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualizer.facultyevaluation'),
        ),
        migrations.AddField(
            model_name='student',
            name='section_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visualizer.section'),
        ),
        migrations.AddField(
            model_name='student',
            name='strand_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visualizer.strand'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='year_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visualizer.yearlevel'),
        ),
        migrations.AddField(
            model_name='principal',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mcluser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='mcluser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
