# Generated by Django 4.1.4 on 2023-01-10 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visualizer', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visualizer.section'),
        ),
        migrations.AddField(
            model_name='student',
            name='strand_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visualizer.strand'),
        ),
    ]
