# Generated by Django 4.1.4 on 2023-02-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_student_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malayanuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'student'), (2, 'teacher'), (3, 'admin')], default=0),
        ),
    ]
