# Generated by Django 4.1.4 on 2023-03-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_malayanuser_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="malayanuser",
            name="user_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "student"),
                    (2, "teacher"),
                    (3, "principal"),
                    (4, "admin"),
                ],
                default=0,
            ),
        ),
    ]
