# Generated by Django 4.1.4 on 2023-01-26 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('start_year', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('end_year', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_ID', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strand_name', models.CharField(choices=[('ABM', 'ABM'), ('ABM-B', 'ABM-B'), ('ABMBUS', 'ABMBUS'), ('HE', 'HE'), ('HUMS', 'HUMS'), ('HUMSS', 'HUMSS'), ('ICT', 'ICT'), ('STEM', 'STEM'), ('STEM-M', 'STEM-M'), ('STEM-S', 'STEM-S'), ('STEMB', 'STEMB'), ('STEMF', 'STEMF'), ('STEMG', 'STEMG'), ('STEMMA', 'STEMMA'), ('STEMSC', 'STEMSC')], default='HUMSS', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=10, unique=True)),
                ('subject_name', models.CharField(default='Subject', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='YearLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ongoing', models.BooleanField(default=False)),
                ('academic_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visualizer.academicyear')),
            ],
        ),
    ]
