# Generated by Django 4.1.4 on 2023-01-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strand',
            name='id',
        ),
        migrations.AlterField(
            model_name='strand',
            name='strand_name',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
