# Generated by Django 4.1.4 on 2022-12-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
