# Generated by Django 4.1.4 on 2022-12-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0002_subject_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(default='subj', max_length=250),
        ),
    ]
