# Generated by Django 4.1.4 on 2023-01-09 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('visualizer', '0003_alter_subject_subject_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('start_year', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('end_year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_ID', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strand_name', models.CharField(choices=[('ABM', 'ABM'), ('ABM-B', 'ABM-B'), ('ABMBUS', 'ABMBUS'), ('HE', 'HE'), ('HUMS', 'HUMS'), ('HUMSS', 'HUMSS'), ('ICT', 'ICT'), ('STEM', 'STEM'), ('STEM-M', 'STEM-M'), ('STEM-S', 'STEM-S'), ('STEMB', 'STEMB'), ('STEMF', 'STEMF'), ('STEMG', 'STEMG'), ('STEMMA', 'STEMMA'), ('STEMSC', 'STEMSC')], default='HUMSS', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.teacher'),
        ),
    ]
