# Generated by Django 4.1.4 on 2023-01-09 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_alter_feedback_academic_year_and_more'),
        ('visualizer', '0004_academicyear_section_strand_remove_teacher_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
